### ISSUE TITLE
cannot find module 'babelify'

### ISSUE THREAD

**Issue by tilgovi** [jokeyrhyme/assertive-chai.js#10]
When I use assertive-chai from a browserify environment, browserify sees the transforms defined in package.json for assertive-chai and tries to load babelify but it is only a dev dependency of assertive-chai, and so it is not installed.

Either it needs to be a peer dependency, regular dependency, or the build process should be changed so that the browserify/transform field isn't in package.json but browserify is only used in a build step, before publishing to npm.

**Comment by jokeyrhyme** [comment]
I want to test this in a few browsers (including IE8) before I tag and publish this to NPM. I should get this done within the next 24 hours. Thanks for being patient. :)

**Comment by jokeyrhyme** [comment]
Tested in Firefox and Chromium on Linux, and Firefox, Chrome, Edge and Internet Explorer 8 through 11. As mentioned in the README.md, ES5-shims should be loaded in IE8 before trying to use assertive-chai.

**Comment by jokeyrhyme** [comment]
v2.0.2 is tagged and published to npm.

Thanks for the report. Let me know if you continue to have issues.
